### ISSUE TITLE
Distill failed for unknown reason

### ISSUE THREAD

**Issue by yoshyosh** [flufff42/RealmTV#1]
When I download the project and hit compile targeting the Apple TV 1080p simulator, I get this `Distill failed for unknown reason` error.

<img width="261" alt="screen shot 2016-06-06 at 11 42 52 am" src="https://cloud.githubusercontent.com/assets/775056/15833492/ebd0e2e4-2bdb-11e6-8f7c-8733c0be5d8e.png">

OSX El Capitan v 10.11.4, Macbook Pro
Xcode 7.3.1

**Comment by seanlabastille** [comment]
Hi @yoshyosh,

this may be a bit of a shot in the dark, but can you check if the files referenced by the asset catalog are actually present on disk?

If not, this may be because you do not have git-lfs [1] set up when cloning.
For example in https://github.com/flufff42/RealmTV/blob/master/Asset%20Sources/Slide%20Positions/Bottom%20Left.png you can see these are stored using LFS.

![screen shot 2016-06-07 at 13 13 51](https://cloud.githubusercontent.com/assets/252173/15855768/b605aa24-2cb1-11e6-9c39-98cf2153c1ca.png)

[1] https://help.github.com/articles/versioning-large-files/

**Comment by seanlabastille** [comment]
This does in fact seem to be the issue.
In particular when downloading the project as a ZIP archive the files stored on LFS are not included.

Please clone the repository normally and then run `git-lfs pull` to fetch the images.

**Comment by yoshyosh** [comment]
oops sorry about that, thanks!
